# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Restaurant.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(800, 620)
        Form.setMinimumSize(QtCore.QSize(800, 620))
        Form.setMaximumSize(QtCore.QSize(800, 620))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.lbl_restName = QtGui.QLabel(Form)
        self.lbl_restName.setGeometry(QtCore.QRect(10, 0, 621, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_restName.setFont(font)
        self.lbl_restName.setObjectName(_fromUtf8("lbl_restName"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(60, 80, 661, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.widget_2 = QtGui.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(180, 90, 611, 321))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.label_5 = QtGui.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 161, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lbl_restMenu = QtGui.QTextEdit(self.widget_2)
        self.lbl_restMenu.setGeometry(QtCore.QRect(0, 30, 611, 291))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_restMenu.setFont(font)
        self.lbl_restMenu.setFrameShape(QtGui.QFrame.VLine)
        self.lbl_restMenu.setFrameShadow(QtGui.QFrame.Plain)
        self.lbl_restMenu.setReadOnly(True)
        self.lbl_restMenu.setObjectName(_fromUtf8("lbl_restMenu"))
        self.lbl_restAddress = QtGui.QLabel(Form)
        self.lbl_restAddress.setGeometry(QtCore.QRect(10, 30, 591, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(10)
        self.lbl_restAddress.setFont(font)
        self.lbl_restAddress.setObjectName(_fromUtf8("lbl_restAddress"))
        self.tradingHours = QtGui.QComboBox(Form)
        self.tradingHours.setGeometry(QtCore.QRect(10, 50, 411, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(10)
        font.setItalic(False)
        self.tradingHours.setFont(font)
        self.tradingHours.setObjectName(_fromUtf8("tradingHours"))
        self.tradingHours.addItem(_fromUtf8(""))
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 90, 181, 321))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.widget.setFont(font)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 161, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lbl_restTags = QtGui.QTextEdit(self.widget)
        self.lbl_restTags.setGeometry(QtCore.QRect(0, 30, 181, 291))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(11)
        font.setItalic(False)
        self.lbl_restTags.setFont(font)
        self.lbl_restTags.setFrameShape(QtGui.QFrame.HLine)
        self.lbl_restTags.setFrameShadow(QtGui.QFrame.Plain)
        self.lbl_restTags.setReadOnly(True)
        self.lbl_restTags.setOverwriteMode(True)
        self.lbl_restTags.setAcceptRichText(True)
        self.lbl_restTags.setObjectName(_fromUtf8("lbl_restTags"))
        self.restaurantRating = QtGui.QLabel(Form)
        self.restaurantRating.setGeometry(QtCore.QRect(650, 30, 141, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(25)
        self.restaurantRating.setFont(font)
        self.restaurantRating.setObjectName(_fromUtf8("restaurantRating"))
        self.userReview = QtGui.QLabel(Form)
        self.userReview.setGeometry(QtCore.QRect(10, 420, 111, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.userReview.setFont(font)
        self.userReview.setObjectName(_fromUtf8("userReview"))
        self.usrReview = QtGui.QTextEdit(Form)
        self.usrReview.setGeometry(QtCore.QRect(0, 440, 181, 171))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        self.usrReview.setFont(font)
        self.usrReview.setObjectName(_fromUtf8("usrReview"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(190, 420, 291, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comments = QtGui.QTextEdit(Form)
        self.comments.setGeometry(QtCore.QRect(180, 440, 611, 171))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(10)
        font.setItalic(False)
        self.comments.setFont(font)
        self.comments.setFrameShape(QtGui.QFrame.VLine)
        self.comments.setFrameShadow(QtGui.QFrame.Plain)
        self.comments.setReadOnly(True)
        self.comments.setObjectName(_fromUtf8("comments"))
        self.thumbsUp = QtGui.QLabel(Form)
        self.thumbsUp.setGeometry(QtCore.QRect(150, 540, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.thumbsUp.setFont(font)
        self.thumbsUp.setObjectName(_fromUtf8("thumbsUp"))
        self.thumbsDown = QtGui.QLabel(Form)
        self.thumbsDown.setGeometry(QtCore.QRect(150, 570, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.thumbsDown.setFont(font)
        self.thumbsDown.setObjectName(_fromUtf8("thumbsDown"))
        self.thumbsUpBtn = QtGui.QPushButton(Form)
        self.thumbsUpBtn.setGeometry(QtCore.QRect(160, 540, 31, 31))
        self.thumbsUpBtn.setObjectName(_fromUtf8("thumbsUpBtn"))
        self.thumbsDownBtn = QtGui.QPushButton(Form)
        self.thumbsDownBtn.setGeometry(QtCore.QRect(160, 570, 31, 31))
        self.thumbsDownBtn.setObjectName(_fromUtf8("thumbsDownBtn"))
        self.thumbsDownBtn.raise_()
        self.thumbsUpBtn.raise_()
        self.lbl_restName.raise_()
        self.line.raise_()
        self.widget_2.raise_()
        self.tradingHours.raise_()
        self.widget.raise_()
        self.restaurantRating.raise_()
        self.lbl_restAddress.raise_()
        self.userReview.raise_()
        self.usrReview.raise_()
        self.label_2.raise_()
        self.comments.raise_()
        self.thumbsUp.raise_()
        self.thumbsDown.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "FoodFinder", None))
        self.lbl_restName.setText(_translate("Form", "Restaurant Name", None))
        self.label_5.setText(_translate("Form", "Menu", None))
        self.lbl_restAddress.setText(_translate("Form", "Address", None))
        self.tradingHours.setItemText(0, _translate("Form", "Trading Hours", None))
        self.label_6.setText(_translate("Form", "Features", None))
        self.restaurantRating.setText(_translate("Form", "Rating", None))
        self.userReview.setText(_translate("Form", "Leave a review!", None))
        self.label_2.setText(_translate("Form", "What have other people had to say?", None))
        self.thumbsUp.setText(_translate("Form", "TextLabel", None))
        self.thumbsDown.setText(_translate("Form", "TextLabel", None))
        self.thumbsUpBtn.setText(_translate("Form", "PushButton", None))
        self.thumbsDownBtn.setText(_translate("Form", "PushButton", None))

