# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Search.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setEnabled(True)
        Form.resize(800, 620)
        Form.setMinimumSize(QtCore.QSize(800, 620))
        Form.setMaximumSize(QtCore.QSize(800, 620))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(11)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet(_fromUtf8("background-image=url(\'bg-1.jpg\')"))
        self.btn_Search = QtGui.QPushButton(Form)
        self.btn_Search.setGeometry(QtCore.QRect(710, 570, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Serif Armenian"))
        font.setBold(True)
        font.setWeight(75)
        self.btn_Search.setFont(font)
        self.btn_Search.setStyleSheet(_fromUtf8(""))
        self.btn_Search.setObjectName(_fromUtf8("btn_Search"))
        self.lbl_Question = QtGui.QLabel(Form)
        self.lbl_Question.setGeometry(QtCore.QRect(180, 20, 431, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Question.setFont(font)
        self.lbl_Question.setAutoFillBackground(False)
        self.lbl_Question.setStyleSheet(_fromUtf8("color:white;text-transform:uppercase;"))
        self.lbl_Question.setObjectName(_fromUtf8("lbl_Question"))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 100, 151, 461))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Serif Armenian"))
        font.setBold(True)
        font.setWeight(75)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color:white;text-transform:uppercase;"))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("color:white;text-transform:uppercase;"))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.S = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setBold(True)
        font.setWeight(75)
        self.S.setFont(font)
        self.S.setStyleSheet(_fromUtf8("color:white;text-transform:uppercase;"))
        self.S.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.S.setObjectName(_fromUtf8("S"))
        self.verticalLayout.addWidget(self.S)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("color:white;text-transform:uppercase;"))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("color:white;text-transform:uppercase;"))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8("color:white;text-transform:uppercase;"))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("color:white;text-transform:uppercase;"))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color:white;text-transform:uppercase;"))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color:white;text-transform:uppercase;"))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("URW Gothic L"))
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("color:white;text-transform:uppercase;"))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.layoutWidget1 = QtGui.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(190, 90, 531, 301))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setBold(False)
        font.setWeight(50)
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setStyleSheet(_fromUtf8(""))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.DiningParty = QtGui.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setBold(False)
        font.setWeight(50)
        self.DiningParty.setFont(font)
        self.DiningParty.setStyleSheet(_fromUtf8(""))
        self.DiningParty.setObjectName(_fromUtf8("DiningParty"))
        self.DiningParty.addItem(_fromUtf8(""))
        self.DiningParty.addItem(_fromUtf8(""))
        self.DiningParty.addItem(_fromUtf8(""))
        self.DiningParty.addItem(_fromUtf8(""))
        self.DiningParty.addItem(_fromUtf8(""))
        self.DiningParty.addItem(_fromUtf8(""))
        self.DiningParty.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.DiningParty)
        self.Cuisine = QtGui.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setBold(False)
        font.setWeight(50)
        self.Cuisine.setFont(font)
        self.Cuisine.setStyleSheet(_fromUtf8(""))
        self.Cuisine.setObjectName(_fromUtf8("Cuisine"))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.Cuisine)
        self.Style = QtGui.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setBold(False)
        font.setWeight(50)
        self.Style.setFont(font)
        self.Style.setStyleSheet(_fromUtf8(""))
        self.Style.setObjectName(_fromUtf8("Style"))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.Style)
        self.Dietary = QtGui.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setBold(False)
        font.setWeight(50)
        self.Dietary.setFont(font)
        self.Dietary.setStyleSheet(_fromUtf8(""))
        self.Dietary.setObjectName(_fromUtf8("Dietary"))
        self.Dietary.addItem(_fromUtf8(""))
        self.Dietary.addItem(_fromUtf8(""))
        self.Dietary.addItem(_fromUtf8(""))
        self.Dietary.addItem(_fromUtf8(""))
        self.Dietary.addItem(_fromUtf8(""))
        self.Dietary.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.Dietary)
        self.Extras = QtGui.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setBold(False)
        font.setWeight(50)
        self.Extras.setFont(font)
        self.Extras.setStyleSheet(_fromUtf8(""))
        self.Extras.setObjectName(_fromUtf8("Extras"))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.Extras)
        self.Sorted = QtGui.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setBold(False)
        font.setWeight(50)
        self.Sorted.setFont(font)
        self.Sorted.setStyleSheet(_fromUtf8(""))
        self.Sorted.setObjectName(_fromUtf8("Sorted"))
        self.Sorted.addItem(_fromUtf8(""))
        self.Sorted.addItem(_fromUtf8(""))
        self.Sorted.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.Sorted)
        self.widget_2 = QtGui.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(190, 420, 531, 151))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.bar_Price = QtGui.QLineEdit(self.widget_2)
        self.bar_Price.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Serif Armenian"))
        font.setBold(True)
        font.setWeight(75)
        self.bar_Price.setFont(font)
        self.bar_Price.setStyleSheet(_fromUtf8(""))
        self.bar_Price.setAlignment(QtCore.Qt.AlignCenter)
        self.bar_Price.setObjectName(_fromUtf8("bar_Price"))
        self.verticalLayout_3.addWidget(self.bar_Price)
        self.bar_Search = QtGui.QLineEdit(self.widget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Serif Armenian"))
        font.setBold(True)
        font.setWeight(75)
        self.bar_Search.setFont(font)
        self.bar_Search.setStyleSheet(_fromUtf8(""))
        self.bar_Search.setAlignment(QtCore.Qt.AlignCenter)
        self.bar_Search.setObjectName(_fromUtf8("bar_Search"))
        self.verticalLayout_3.addWidget(self.bar_Search)
        self.bar_Location = QtGui.QLineEdit(self.widget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Serif Armenian"))
        font.setBold(True)
        font.setWeight(75)
        self.bar_Location.setFont(font)
        self.bar_Location.setStyleSheet(_fromUtf8(""))
        self.bar_Location.setAlignment(QtCore.Qt.AlignCenter)
        self.bar_Location.setObjectName(_fromUtf8("bar_Location"))
        self.verticalLayout_3.addWidget(self.bar_Location)
        self.view = QtGui.QWidget(Form)
        self.view.setGeometry(QtCore.QRect(200, 390, 511, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Serif Armenian"))
        font.setBold(True)
        font.setWeight(75)
        self.view.setFont(font)
        self.view.setStyleSheet(_fromUtf8("background-color:white;"))
        self.view.setObjectName(_fromUtf8("view"))
        self.ViewAny = QtGui.QRadioButton(self.view)
        self.ViewAny.setGeometry(QtCore.QRect(9, 0, 119, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setBold(False)
        font.setWeight(50)
        self.ViewAny.setFont(font)
        self.ViewAny.setAutoFillBackground(False)
        self.ViewAny.setStyleSheet(_fromUtf8(""))
        self.ViewAny.setChecked(True)
        self.ViewAny.setObjectName(_fromUtf8("ViewAny"))
        self.ViewWaterFront = QtGui.QRadioButton(self.view)
        self.ViewWaterFront.setGeometry(QtCore.QRect(120, 0, 119, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setBold(False)
        font.setWeight(50)
        self.ViewWaterFront.setFont(font)
        self.ViewWaterFront.setStyleSheet(_fromUtf8(""))
        self.ViewWaterFront.setObjectName(_fromUtf8("ViewWaterFront"))
        self.ViewScenic = QtGui.QRadioButton(self.view)
        self.ViewScenic.setGeometry(QtCore.QRect(280, 0, 118, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setBold(False)
        font.setWeight(50)
        self.ViewScenic.setFont(font)
        self.ViewScenic.setStyleSheet(_fromUtf8(""))
        self.ViewScenic.setObjectName(_fromUtf8("ViewScenic"))
        self.ViewBeachFront = QtGui.QRadioButton(self.view)
        self.ViewBeachFront.setGeometry(QtCore.QRect(400, 0, 119, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setBold(False)
        font.setWeight(50)
        self.ViewBeachFront.setFont(font)
        self.ViewBeachFront.setStyleSheet(_fromUtf8(""))
        self.ViewBeachFront.setObjectName(_fromUtf8("ViewBeachFront"))
        self.btn = QtGui.QPushButton(Form)
        self.btn.setGeometry(QtCore.QRect(730, 10, 61, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Serif Armenian"))
        font.setBold(True)
        font.setWeight(75)
        self.btn.setFont(font)
        self.btn.setObjectName(_fromUtf8("btn"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "FoodFinder", None))
        self.btn_Search.setText(_translate("Form", "Search", None))
        self.lbl_Question.setText(_translate("Form", "W h e r e   w o u l d   y o u   l i k e   t o   e a t   t o d a y ?", None))
        self.label_2.setText(_translate("Form", "Dining Party", None))
        self.label_5.setText(_translate("Form", "Cuisine", None))
        self.S.setText(_translate("Form", "Style", None))
        self.label_6.setText(_translate("Form", "Dietary", None))
        self.label_7.setText(_translate("Form", "Extras", None))
        self.label_9.setText(_translate("Form", "Sorted by", None))
        self.label_8.setText(_translate("Form", "View", None))
        self.label.setText(_translate("Form", "Price", None))
        self.label_4.setText(_translate("Form", "Restaurant Name", None))
        self.label_10.setText(_translate("Form", "Location", None))
        self.DiningParty.setItemText(0, _translate("Form", "Any", None))
        self.DiningParty.setItemText(1, _translate("Form", "Solo", None))
        self.DiningParty.setItemText(2, _translate("Form", "Couple", None))
        self.DiningParty.setItemText(3, _translate("Form", "Large-Group", None))
        self.DiningParty.setItemText(4, _translate("Form", "Pet-Friendly", None))
        self.DiningParty.setItemText(5, _translate("Form", "Take-away", None))
        self.DiningParty.setItemText(6, _translate("Form", "Child-Friendly", None))
        self.Cuisine.setItemText(0, _translate("Form", "Any", None))
        self.Cuisine.setItemText(1, _translate("Form", "Cafe", None))
        self.Cuisine.setItemText(2, _translate("Form", "Chinese", None))
        self.Cuisine.setItemText(3, _translate("Form", "Burgers", None))
        self.Cuisine.setItemText(4, _translate("Form", "American", None))
        self.Cuisine.setItemText(5, _translate("Form", "Fusion", None))
        self.Cuisine.setItemText(6, _translate("Form", "Dessert", None))
        self.Cuisine.setItemText(7, _translate("Form", "Pizza", None))
        self.Cuisine.setItemText(8, _translate("Form", "Italian", None))
        self.Cuisine.setItemText(9, _translate("Form", "Lebanese", None))
        self.Cuisine.setItemText(10, _translate("Form", "Barbeque", None))
        self.Cuisine.setItemText(11, _translate("Form", "Japanese", None))
        self.Cuisine.setItemText(12, _translate("Form", "Indian", None))
        self.Cuisine.setItemText(13, _translate("Form", "Seafood", None))
        self.Cuisine.setItemText(14, _translate("Form", "Indonesian", None))
        self.Cuisine.setItemText(15, _translate("Form", "Finger-Food", None))
        self.Cuisine.setItemText(16, _translate("Form", "Breakfast", None))
        self.Style.setItemText(0, _translate("Form", "Any", None))
        self.Style.setItemText(1, _translate("Form", "Casual-Dining", None))
        self.Style.setItemText(2, _translate("Form", "Cozy", None))
        self.Style.setItemText(3, _translate("Form", "Modern", None))
        self.Style.setItemText(4, _translate("Form", "Fine-dining", None))
        self.Style.setItemText(5, _translate("Form", "Fast-food", None))
        self.Style.setItemText(6, _translate("Form", "Authentic", None))
        self.Style.setItemText(7, _translate("Form", "Street Style", None))
        self.Dietary.setItemText(0, _translate("Form", "Any", None))
        self.Dietary.setItemText(1, _translate("Form", "Vegetarian-Friendly", None))
        self.Dietary.setItemText(2, _translate("Form", "Vegan-Friendly", None))
        self.Dietary.setItemText(3, _translate("Form", "Halal", None))
        self.Dietary.setItemText(4, _translate("Form", "Gluten-Free", None))
        self.Dietary.setItemText(5, _translate("Form", "Vegetarian", None))
        self.Extras.setItemText(0, _translate("Form", "Any", None))
        self.Extras.setItemText(1, _translate("Form", "Wheelchair-Accessible", None))
        self.Extras.setItemText(2, _translate("Form", "Bookings-Accepted", None))
        self.Extras.setItemText(3, _translate("Form", "Bar", None))
        self.Extras.setItemText(4, _translate("Form", "BYO", None))
        self.Extras.setItemText(5, _translate("Form", "Cash-Only", None))
        self.Extras.setItemText(6, _translate("Form", "Smoking-Area", None))
        self.Extras.setItemText(7, _translate("Form", "Functions", None))
        self.Extras.setItemText(8, _translate("Form", "Outdoor-Area", None))
        self.Extras.setItemText(9, _translate("Form", "Beer-Garden", None))
        self.Extras.setItemText(10, _translate("Form", "Home-Delivery", None))
        self.Sorted.setItemText(0, _translate("Form", "Rating", None))
        self.Sorted.setItemText(1, _translate("Form", "Price", None))
        self.Sorted.setItemText(2, _translate("Form", "Alphabetical", None))
        self.ViewAny.setText(_translate("Form", "Any", None))
        self.ViewWaterFront.setText(_translate("Form", "Water Front", None))
        self.ViewScenic.setText(_translate("Form", "Scenic", None))
        self.ViewBeachFront.setText(_translate("Form", "Beach Front", None))
        self.btn.setText(_translate("Form", "Close All", None))

