# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Search.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setEnabled(True)
        Form.resize(800, 620)
        Form.setMinimumSize(QtCore.QSize(800, 620))
        Form.setMaximumSize(QtCore.QSize(800, 620))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.bar_Search = QtGui.QLineEdit(Form)
        self.bar_Search.setGeometry(QtCore.QRect(210, 480, 391, 31))
        self.bar_Search.setObjectName(_fromUtf8("bar_Search"))
        self.btn_Search = QtGui.QPushButton(Form)
        self.btn_Search.setGeometry(QtCore.QRect(350, 550, 101, 31))
        self.btn_Search.setObjectName(_fromUtf8("btn_Search"))
        self.lbl_Question = QtGui.QLabel(Form)
        self.lbl_Question.setGeometry(QtCore.QRect(230, 10, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_Question.setFont(font)
        self.lbl_Question.setAutoFillBackground(False)
        self.lbl_Question.setObjectName(_fromUtf8("lbl_Question"))
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 41, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.bar_Price = QtGui.QLineEdit(Form)
        self.bar_Price.setGeometry(QtCore.QRect(210, 420, 391, 31))
        self.bar_Price.setObjectName(_fromUtf8("bar_Price"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 420, 61, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(67, 80, 111, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.S = QtGui.QLabel(Form)
        self.S.setGeometry(QtCore.QRect(110, 180, 51, 20))
        self.S.setObjectName(_fromUtf8("S"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(80, 480, 121, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(100, 130, 68, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(100, 240, 68, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(100, 290, 68, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.ViewWaterFront = QtGui.QRadioButton(Form)
        self.ViewWaterFront.setGeometry(QtCore.QRect(370, 380, 111, 22))
        self.ViewWaterFront.setObjectName(_fromUtf8("ViewWaterFront"))
        self.ViewBeachFront = QtGui.QRadioButton(Form)
        self.ViewBeachFront.setGeometry(QtCore.QRect(490, 380, 111, 22))
        self.ViewBeachFront.setObjectName(_fromUtf8("ViewBeachFront"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(110, 380, 68, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.ViewAny = QtGui.QRadioButton(Form)
        self.ViewAny.setGeometry(QtCore.QRect(210, 380, 51, 22))
        self.ViewAny.setChecked(True)
        self.ViewAny.setObjectName(_fromUtf8("ViewAny"))
        self.ViewScenic = QtGui.QRadioButton(Form)
        self.ViewScenic.setGeometry(QtCore.QRect(280, 380, 71, 22))
        self.ViewScenic.setObjectName(_fromUtf8("ViewScenic"))
        self.DiningParty = QtGui.QComboBox(Form)
        self.DiningParty.setGeometry(QtCore.QRect(210, 80, 391, 27))
        self.DiningParty.setObjectName(_fromUtf8("DiningParty"))
        self.DiningParty.addItem(_fromUtf8(""))
        self.DiningParty.addItem(_fromUtf8(""))
        self.DiningParty.addItem(_fromUtf8(""))
        self.DiningParty.addItem(_fromUtf8(""))
        self.DiningParty.addItem(_fromUtf8(""))
        self.DiningParty.addItem(_fromUtf8(""))
        self.DiningParty.addItem(_fromUtf8(""))
        self.Cuisine = QtGui.QComboBox(Form)
        self.Cuisine.setGeometry(QtCore.QRect(210, 130, 391, 27))
        self.Cuisine.setObjectName(_fromUtf8("Cuisine"))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Cuisine.addItem(_fromUtf8(""))
        self.Style = QtGui.QComboBox(Form)
        self.Style.setGeometry(QtCore.QRect(210, 180, 391, 27))
        self.Style.setObjectName(_fromUtf8("Style"))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.Style.addItem(_fromUtf8(""))
        self.Dietary = QtGui.QComboBox(Form)
        self.Dietary.setGeometry(QtCore.QRect(210, 240, 391, 27))
        self.Dietary.setObjectName(_fromUtf8("Dietary"))
        self.Dietary.addItem(_fromUtf8(""))
        self.Dietary.addItem(_fromUtf8(""))
        self.Dietary.addItem(_fromUtf8(""))
        self.Dietary.addItem(_fromUtf8(""))
        self.Dietary.addItem(_fromUtf8(""))
        self.Dietary.addItem(_fromUtf8(""))
        self.Extras = QtGui.QComboBox(Form)
        self.Extras.setGeometry(QtCore.QRect(210, 290, 391, 27))
        self.Extras.setObjectName(_fromUtf8("Extras"))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.Extras.addItem(_fromUtf8(""))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(100, 340, 68, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.Sorted = QtGui.QComboBox(Form)
        self.Sorted.setGeometry(QtCore.QRect(210, 340, 391, 27))
        self.Sorted.setObjectName(_fromUtf8("Sorted"))
        self.Sorted.addItem(_fromUtf8(""))
        self.Sorted.addItem(_fromUtf8(""))
        self.Sorted.addItem(_fromUtf8(""))

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.btn_Search, QtCore.SIGNAL(_fromUtf8("released()")), self.bar_Price.clear)
        QtCore.QObject.connect(self.btn_Search, QtCore.SIGNAL(_fromUtf8("released()")), self.bar_Search.undo)
        QtCore.QObject.connect(self.btn_Search, QtCore.SIGNAL(_fromUtf8("released()")), self.bar_Search.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.bar_Search, self.btn_Search)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "FoodFinder", None))
        self.btn_Search.setText(_translate("Form", "Search", None))
        self.lbl_Question.setText(_translate("Form", "Where would you like to eat today?", None))
        self.pushButton.setText(_translate("Form", "Exit", None))
        self.label.setText(_translate("Form", "Price", None))
        self.label_2.setText(_translate("Form", "Dining Party", None))
        self.S.setText(_translate("Form", "Style", None))
        self.label_4.setText(_translate("Form", "Restaurant Name", None))
        self.label_5.setText(_translate("Form", "Cuisine", None))
        self.label_6.setText(_translate("Form", "Dietary", None))
        self.label_7.setText(_translate("Form", "Extras", None))
        self.ViewWaterFront.setText(_translate("Form", "Water Front", None))
        self.ViewBeachFront.setText(_translate("Form", "Beach Front", None))
        self.label_8.setText(_translate("Form", "View", None))
        self.ViewAny.setText(_translate("Form", "Any", None))
        self.ViewScenic.setText(_translate("Form", "Scenic", None))
        self.DiningParty.setItemText(0, _translate("Form", "Any", None))
        self.DiningParty.setItemText(1, _translate("Form", "Solo", None))
        self.DiningParty.setItemText(2, _translate("Form", "Couple", None))
        self.DiningParty.setItemText(3, _translate("Form", "Large-Group", None))
        self.DiningParty.setItemText(4, _translate("Form", "Pet-Friendly", None))
        self.DiningParty.setItemText(5, _translate("Form", "Take-away", None))
        self.DiningParty.setItemText(6, _translate("Form", "Child-Friendly", None))
        self.Cuisine.setItemText(0, _translate("Form", "Any", None))
        self.Cuisine.setItemText(1, _translate("Form", "Cafe", None))
        self.Cuisine.setItemText(2, _translate("Form", "Chinese", None))
        self.Cuisine.setItemText(3, _translate("Form", "Burgers", None))
        self.Cuisine.setItemText(4, _translate("Form", "American", None))
        self.Cuisine.setItemText(5, _translate("Form", "Fusion", None))
        self.Cuisine.setItemText(6, _translate("Form", "Dessert", None))
        self.Cuisine.setItemText(7, _translate("Form", "Pizza", None))
        self.Cuisine.setItemText(8, _translate("Form", "Italian", None))
        self.Cuisine.setItemText(9, _translate("Form", "Lebanese", None))
        self.Cuisine.setItemText(10, _translate("Form", "Barbeque", None))
        self.Cuisine.setItemText(11, _translate("Form", "Japanese", None))
        self.Cuisine.setItemText(12, _translate("Form", "Indian", None))
        self.Cuisine.setItemText(13, _translate("Form", "Seafood", None))
        self.Cuisine.setItemText(14, _translate("Form", "Indonesian", None))
        self.Cuisine.setItemText(15, _translate("Form", "Finger-Food", None))
        self.Cuisine.setItemText(16, _translate("Form", "Breakfast", None))
        self.Style.setItemText(0, _translate("Form", "Any", None))
        self.Style.setItemText(1, _translate("Form", "Casual-Dining", None))
        self.Style.setItemText(2, _translate("Form", "Cozy", None))
        self.Style.setItemText(3, _translate("Form", "Modern", None))
        self.Style.setItemText(4, _translate("Form", "Fine-dining", None))
        self.Style.setItemText(5, _translate("Form", "Fast-food", None))
        self.Style.setItemText(6, _translate("Form", "Authentic", None))
        self.Style.setItemText(7, _translate("Form", "Street Style", None))
        self.Dietary.setItemText(0, _translate("Form", "Any", None))
        self.Dietary.setItemText(1, _translate("Form", "Vegetarian-Friendly", None))
        self.Dietary.setItemText(2, _translate("Form", "Vegan-Friendly", None))
        self.Dietary.setItemText(3, _translate("Form", "Halal", None))
        self.Dietary.setItemText(4, _translate("Form", "Gluten-Free", None))
        self.Dietary.setItemText(5, _translate("Form", "Vegetarian", None))
        self.Extras.setItemText(0, _translate("Form", "Any", None))
        self.Extras.setItemText(1, _translate("Form", "Wheelchair-Accessible", None))
        self.Extras.setItemText(2, _translate("Form", "Bookings-Accepted", None))
        self.Extras.setItemText(3, _translate("Form", "Bar", None))
        self.Extras.setItemText(4, _translate("Form", "BYO", None))
        self.Extras.setItemText(5, _translate("Form", "Cash-Only", None))
        self.Extras.setItemText(6, _translate("Form", "Smoking-Area", None))
        self.Extras.setItemText(7, _translate("Form", "Functions", None))
        self.Extras.setItemText(8, _translate("Form", "Outdoor-Area", None))
        self.Extras.setItemText(9, _translate("Form", "Beer-Garden", None))
        self.Extras.setItemText(10, _translate("Form", "Home-Delivery", None))
        self.label_9.setText(_translate("Form", "Sorted", None))
        self.Sorted.setItemText(0, _translate("Form", "Rating", None))
        self.Sorted.setItemText(1, _translate("Form", "Price ", None))
        self.Sorted.setItemText(2, _translate("Form", "Alphabetical", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

